package com.myspace.nsp_jpa_query;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class mst_states implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "MST_STATES_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "MST_STATES_ID_SEQ", name = "MST_STATES_ID_GENERATOR")
	private java.lang.Long id;

	private java.lang.Character pfms_state_code;

	private java.lang.String state_name;

	private java.lang.String short_name;

	private java.lang.Boolean delete_flag;

	private java.lang.Character state_ut;

	private java.lang.Boolean is_north_east;

	private String state_id;

	public mst_states() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Character getPfms_state_code() {
		return this.pfms_state_code;
	}

	public void setPfms_state_code(java.lang.Character pfms_state_code) {
		this.pfms_state_code = pfms_state_code;
	}

	public java.lang.String getState_name() {
		return this.state_name;
	}

	public void setState_name(java.lang.String state_name) {
		this.state_name = state_name;
	}

	public java.lang.String getShort_name() {
		return this.short_name;
	}

	public void setShort_name(java.lang.String short_name) {
		this.short_name = short_name;
	}

	public java.lang.Boolean getDelete_flag() {
		return this.delete_flag;
	}

	public void setDelete_flag(java.lang.Boolean delete_flag) {
		this.delete_flag = delete_flag;
	}

	public java.lang.Character getState_ut() {
		return this.state_ut;
	}

	public void setState_ut(java.lang.Character state_ut) {
		this.state_ut = state_ut;
	}

	public java.lang.Boolean getIs_north_east() {
		return this.is_north_east;
	}

	public void setIs_north_east(java.lang.Boolean is_north_east) {
		this.is_north_east = is_north_east;
	}

	@Override
	public java.lang.String toString() {
		return "mst_states [id=" + id + ", pfms_state_code=" + pfms_state_code
				+ ", state_name=" + state_name + "]";
	}

	public java.lang.String getState_id() {
		return this.state_id;
	}

	public void setState_id(java.lang.String state_id) {
		this.state_id = state_id;
	}

	public mst_states(java.lang.Long id, java.lang.Character pfms_state_code,
			java.lang.String state_name, java.lang.String short_name,
			java.lang.Boolean delete_flag, java.lang.Character state_ut,
			java.lang.Boolean is_north_east, java.lang.String state_id) {
		this.id = id;
		this.pfms_state_code = pfms_state_code;
		this.state_name = state_name;
		this.short_name = short_name;
		this.delete_flag = delete_flag;
		this.state_ut = state_ut;
		this.is_north_east = is_north_east;
		this.state_id = state_id;
	}

}